Package: common-tutorials
Version: 3.4.5
Section: misc
Priority: extra
Architecture: any
Depends: ${misc:Depends} python-empy, cmake, make, 
         @(CATKIN_PACKAGE_PREFIX)genmsg, @(CATKIN_PACKAGE_PREFIX)genpy, @(CATKIN_PACKAGE_PREFIX)gencpp,
Build-Depends: debhelper (>= 7), cmake, gcc, make, python, python-empy, python-setuptools, 
               @(CATKIN_PACKAGE_PREFIX)catkin, @(CATKIN_PACKAGE_PREFIX)genmsg, 
               @(CATKIN_PACKAGE_PREFIX)genpy, @(CATKIN_PACKAGE_PREFIX)gencpp,
Description: common_tutorials
Author: 
Maintainer: 
Homepage: http://www.ros.org/wiki/common_tutorials

Catkin-ProjectName: common_tutorials
Catkin-CopyrightType:  willowgarage
Catkin-Depends: catkin, actionlib
Catkin-DebRulesType: cmake
